services:
  - type: web
    name: inventory-pos-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn inventory_pos.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: inventory-pos-app
          property: host
    disks:
      - name: media
        mountPath: /media
    static:
      - name: static
        path: staticfiles
      - name: media
        path: media

databases:
  - name: inventory-pos-db
    databaseName: inventory_pos
    user: postgres